spring:
  cloud:
    gateway:
      routes:
        - id: user-management-service
          uri: lb://user-management-service
          predicates:
            - Path=/auth/**
        - id: catalog-service
          uri: lb://design-pattern-catalog-service
          predicates:
            - Path=/patterns/**
        - id: recommendation-service
          uri: lb://recommendation-engine-service
          predicates:
            - Path=/recommendations/**
        - id: ai-service
          uri: lb://ai-helper-service
          predicates:
            - Path=/ai/**
        - id: design-pattern-generator
          uri: lb://design-pattern-generator
          predicates:
            - Path=/api/analyze/**
        - id: pattern-analyzer
          uri: lb://design-pattern-generator
          predicates:
            - Path=/api/analyze/**

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  metrics:
    tags:
      application: ${spring.application.name}
  tracing:
    sampling:
      probability: 1.0
    zipkin:
      base-url: http://zipkin:9411
  prometheus:
    metrics:
      export:
        enabled: true

logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"