spring:
  cloud:
    gateway:
      routes:
        - id: user-management-service
          uri: lb://user-management-service
          predicates:
            - Path=/auth/**
        - id: catalog-service
          uri: lb://design-pattern-catalog-service
          predicates:
            - Path=/design_patterns/**
        - id: recommendation-service
          uri: lb://recommendation-engine-service
          predicates:
            - Path=/recommendations/**
        - id: ai-service
          uri: lb://ai-helper-service
          predicates:
            - Path=/ai/**