spring:
  cloud:
    gateway:
      routes:
        - id: user-management-service
          uri: lb://user-management-service
          predicates:
            - Path=/auth/**
        - id: catalog-service
          uri: lb://design-pattern-catalog-service
          predicates:
            - Path=/patterns/**
        - id: recommendation-service
          uri: lb://recommendation-engine-service
          predicates:
            - Path=/recommendations/**
        - id: ai-service
          uri: lb://ai-helper-service
          predicates:
            - Path=/ai/**
      default-filters:
        - TraceId
      filter:
        trace-id:
          enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  metrics:
    tags:
      application: ${spring.application.name}
    distribution:
      percentiles-histogram:
        http.server.requests: true
  tracing:
    sampling:
      probability: 1.0
    propagation:
      type: w3c
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans

logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"