name: CI/CD Pipeline

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

env:
  REGISTRY: ghcr.io
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: Zaratapa1
  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    services:
      postgres-user:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: Zaratapa1
          POSTGRES_DB: user_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      
      postgres-catalog:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: Zaratapa1
          POSTGRES_DB: catalog_db
        ports:
          - 5433:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    # Build all services first
    - name: Build Service Registry
      run: |
        cd service-registry
        chmod +x mvnw
        ./mvnw clean package -DskipTests
        mkdir -p target/docker
        cp target/*.jar target/docker/app.jar

    - name: Build User Management Service
      run: |
        cd user-management-service
        chmod +x mvnw
        ./mvnw clean package -DskipTests
        mkdir -p target/docker
        cp target/*.jar target/docker/app.jar

    - name: Build Design Pattern Catalog Service
      run: |
        cd design-pattern-catalog-service
        chmod +x mvnw
        ./mvnw clean package -DskipTests
        mkdir -p target/docker
        cp target/*.jar target/docker/app.jar

    # Upload artifacts
    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: build-artifacts
        path: |
          */target/docker/app.jar
        retention-days: 1

  docker-build-push:
    needs: build-and-test
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    
    steps:
    - uses: actions/checkout@v3
    
    # Download artifacts from previous job
    - name: Download build artifacts
      uses: actions/download-artifact@v3
      with:
        name: build-artifacts
        path: .

    - name: Set lowercase repository owner
      run: |
        echo "OWNER=${GITHUB_REPOSITORY_OWNER,,}" >> $GITHUB_ENV

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    # Build and push Service Registry
    - name: Build and push Service Registry
      run: |
        echo "Building service-registry..."
        cd service-registry
        cp ../service-registry/target/docker/app.jar app.jar
        docker build -t ${{ env.REGISTRY }}/${{ env.OWNER }}/design-pattern/service-registry:latest .
        echo "Pushing service-registry..."
        docker push ${{ env.REGISTRY }}/${{ env.OWNER }}/design-pattern/service-registry:latest

    # Build and push User Management Service
    - name: Build and push User Management Service
      run: |
        echo "Building user-management..."
        cd user-management-service
        cp ../user-management-service/target/docker/app.jar app.jar
        docker build -t ${{ env.REGISTRY }}/${{ env.OWNER }}/design-pattern/user-management:latest .
        echo "Pushing user-management..."
        docker push ${{ env.REGISTRY }}/${{ env.OWNER }}/design-pattern/user-management:latest

    # Continue with other services...