name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Make mvnw executable
      run: |
        chmod +x ./user-management-service/mvnw
        
    - name: Build with Maven
      run: |
        cd user-management-service
        ./mvnw clean package

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and Push Docker image
      run: |
        docker build -t ghcr.io/${{ github.repository }}/user-management-service:latest ./user-management-service
        docker push ghcr.io/${{ github.repository }}/user-management-service:latest
